apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: chatbotsocket
  labels:
    app: chatbotsocket
data:
  NODE_ENV: "production"
  PORT: "3100"
  HOSTNAME: "0.0.0.0"
  NEXTAUTH_URL: "http://chatbotsocket.com"
